name: .NET Core

on: [push]

jobs:
  osxbuild:
    name: MacOS build

    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet publish -r osx-x64 -c Release
    - uses: actions/upload-artifact@v1
      with:
        name: obj2difSharp-macos-x64
        path: obj2difSharp/bin/Release/netcoreapp3.1/osx-x64/publish/obj2difSharp
          
  winbuild:
    name: Windows Build

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet publish -r win-x64 -c Release
    - uses: actions/upload-artifact@v1
      with:
        name: obj2difSharp-win-x64
        path: obj2difSharp\bin\Release\netcoreapp3.1\win-x64\publish\obj2difSharp.exe
 
  release:
    name: "Release"
    runs-on: "ubuntu-latest"  
    needs: [osxbuild,winbuild]
    
    steps:
      # ...
      
    - uses: actions/checkout@v1

    - uses: actions/download-artifact@v1
      with:
        name: obj2difSharp-win-x64
        path: obj2difSharp-win-x64.exe
        
    - uses: actions/download-artifact@v1
      with:
        name: obj2difSharp-macos-x64
        path: obj2difSharp-macos-x64

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          automatic_release_tag: auto-build
          title: obj2difPlus
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            obj2difSharp-win-x64.exe
            obj2difSharp-macos-x64
